mu: 0.
L: 10
eta: 1  # final step size = eta / L 
dim: 200
delta: 0.5
R: 5

K_min: 1
K_max: 50

alg: grad_desc  # grad_desc or nesterov_grad_desc
dro_obj: cvar  # expectation or cvar
dro_pep_obj: obj_val  # obj_val or grad_sq_norm or opt_dist_sq_norm

seed:
  full_samples: 0
  train: 100

sample_N: 10000

training:
  expectation_N: 100
  cvar_N: 10
num_clusters:
  expectation: 1
<<<<<<< Updated upstream
  cvar: 20
=======
  cvar: null
>>>>>>> Stashed changes

sample_fname: samples.csv
pep_fname: pep.csv
dro_fname: dro.csv

eps:
  log_min: -3
  log_max: 0
  logspace_count: 4
alpha: 0.1