mu: 0.
L: 5
eta: 1  # final step size = eta / L 
dim: 100
delta: 0.5
R: 5

K_min: 1
K_max: 50

alg: nesterov_grad_desc  # grad_desc or nesterov_grad_desc
dro_obj: cvar  # expectation or cvar
dro_pep_obj: obj_val  # obj_val or grad_sq_norm or opt_dist_sq_norm

precond_type: average # 'average' or 'max' or 'min'

seed:
  full_samples: 0
  train: 101

sample_N: 1000

training:
  expectation_N: 1000
  cvar_N: 1000
num_clusters:
  expectation: 20
  cvar: 20

sample_fname: samples.csv
pep_fname: pep.csv
dro_fname: dro.csv

eps:
  log_min: -4
  log_max: -2
  logspace_count: 7
alpha: 0.1