m: 200
n: 300
eta: 1
lambd: 0.1

R: 9.919344468 # this is found experimentally from out of sample data

K_min: 1
K_max: 25

seed:
  A: 0
  out_of_sample: 10
  in_sample: 20

p_A_nonzero: 0.4
p_xsamp_nonzero: 0.25
N: 100
noise_eps: 0.001

alg: ista  # ista or fista or optista
dro_obj: expectation  # expectation or cvar
pep_obj: obj_val  # obj_val or grad_sq_norm or opt_dist_sq_norm

precond_type: average # 'average' or 'max' or 'min'

training:
  expectation_N: 100
  cvar_N: 100
num_clusters:
  expectation: null
  cvar: null

sample_fname: samples.csv
pep_fname: pep.csv
dro_fname: dro.csv

eps:
  log_min: 0
  log_max: 1
  logspace_count: 3
alpha: 0.1