m: 100
n: 200
eta: 1
lambd: 0.01

K_min: 1
K_max: 2

seed:
  A: 0

p_A_nonzero: 0.3
p_xsamp_nonzero: 0.25
N: 100
noise_eps: 0.001

alg: ista  # ista or fista or optista
dro_obj: expectation  # expectation or cvar
pep_obj: obj_val  # obj_val or grad_sq_norm or opt_dist_sq_norm

precond_type: average # 'average' or 'max' or 'min'