sample_frac: 0.25
delta: 1e-2
R: 1
eta: 0.159

L: 6.3 # FILL THIS IN ONCE KNOWN

K_min: 26
K_max: 30

alg: nesterov_fgm  # grad_desc or nesterov_grad_desc or nesterov_fgm
dro_obj: expectation  # expectation or cvar
dro_pep_obj: obj_val  # obj_val or grad_sq_norm or opt_dist_sq_norm

precond_type: average # 'average' or 'max' or 'min'

seed:
  full_samples: 0
  train: 1010

sample_N: 1000

training:
  expectation_N: 100
  cvar_N: 100
  lyap_N: 100
num_clusters:
  expectation: null
  cvar: null

sample_fname: samples.csv
pep_fname: pep.csv
dro_fname: dro.csv

eps:
  log_min: -2
  log_max: -1
  logspace_count: 4
alpha: 0.1