mu: 0.
L: 10
eta: 0.5  # final step size = eta / L 
dim: 200
R: 5

K_min: 1
K_max: 100

alg: grad_desc  # grad_desc or nesterov_grad_desc
dro_obj: cvar  # expectation or cvar
dro_pep_obj: grad_sq_norm  # obj_val or grad_sq_norm or opt_dist_sq_norm

seed:
  full_samples: 0
  train: 100

sample_N: 10000

training:
  expectation_N: 100
  cvar_N: 100
num_clusters:
  expectation: 1
  cvar: 10

sample_fname: samples.csv
pep_fname: pep.csv
dro_fname: dro.csv

eps:
  log_min: -3
  log_max: 0
  logspace_count: 20
alpha: 0.1