mu: 0.
L: 1
eta: 1  # final step size = eta / L 
dim: 100
R: 5

K_min: 1
K_max: 30

alg: nesterov_grad_desc  # grad_desc or nesterov_grad_desc
dro_obj: cvar  # expectation or cvar
dro_pep_obj: obj_val  # obj_val or grad_sq_norm or opt_dist_sq_norm

precond_type: average # 'average' or 'max' or 'min'

seed:
  full_samples: 0
  train: 100

sample_N: 10000

training:
  expectation_N: 1
  cvar_N: 20
  lyap_N: 25
num_clusters:
  expectation: null
  cvar: null

sample_fname: samples.csv
pep_fname: pep.csv
dro_fname: dro.csv

eps:
  log_min: -1
  log_max: 1
  logspace_count: 7
alpha: 0.1